package com.ella.roulette.ui.entities

import android.graphics.drawable.Drawable
import android.net.Uri

data class Beverage(
    var name: String? = null,
    var pictureUri: Uri? = null,
    var pictureDrawable: Drawable? = null,
    var owner: String? = null,
    var description: String? = null,
)

object Helper {
    val beverages: ArrayList<Beverage>
        get() {
            return ArrayList<Beverage>().apply {
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
                add(Beverage(name = "Beer"))
                add(Beverage(name = "Sprite"))
                add(Beverage(name = "Fanta"))
                add(Beverage(name = "Vodka"))
                add(Beverage(name = "Water"))
                add(Beverage(name = "Starka"))
            }
        }
}